In [3]:
#Write a NumPy program to print the NumPy version in your system.
import numpy as np
print(np.version)

<module 'numpy.version' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>


In [1]:
import numpy as np
a=np.mat([[2,3,4],[5,6,7],[8,9,10]])
a

matrix([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]])

In [4]:
##Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.
l=[12.23, 13.32, 100, 36.32]
a=np.array(l)
a

array([ 12.23,  13.32, 100.  ,  36.32])

In [5]:
#Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. 
import numpy as np
a=np.arange(2,11).reshape(3,3)
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [7]:
#Write a NumPy program to create an array with values ranging from 12 to 38.
a=np.arange(12,39)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

In [8]:
#Write a NumPy program to create a null vector of size 10 and update sixth value to 11.
import numpy as np
a=np.zeros(10)
a
a[6]=11
a

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

In [18]:
#Write a NumPy program to reverse an array (first element becomes last). 
a=np.arange(12,40)
print(a,'original range')
x=a[::-1]
print(x,'after reverse')

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39] original range
[39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16
 15 14 13 12] after reverse


In [42]:
#Write a NumPy program to convert an array to a float type.x
x=[1, 2, 3, 4]
print(x)
x1=np.array(x,dtype=float)
x1

[1, 2, 3, 4]


array([1., 2., 3., 4.])

In [55]:
##Write a NumPy program to create a 2d array with 1 on the border and 0 inside
import numpy as np
x=np.ones([5,4])
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [104]:
#Write a NumPy program to convert a list and tuple into arrays.
list1=[1,2,3,4,5,6,7,8]
x1=np.array(list1)
print(x1)
tuple1=([8, 4, 6], [1, 2, 3])
z1=np.array(tuple1)
print(z1)



[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


In [107]:
#Write a NumPy program to append values to the end of an array. 
#Original array:
#[10, 20, 30]
#After append values to the end of the array:
#[10 20 30 40 50 60 70 80 90]
z=[10, 20, 30]
x=np.array(z)
x1=np.append(x,[[40,50,60],[70,80,90]])
x1


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [122]:
#Write a NumPy program to create an empty and a full array.
import numpy as np
x=np.empty([3,4])
print(x)
z=np.full([3,3],6)
z

[[1.15066736e-311 1.15067620e-311 1.15067620e-311 1.15067620e-311]
 [1.15067620e-311 1.15067620e-311 1.15067623e-311 1.15067623e-311]
 [1.15067623e-311 1.15067620e-311 1.15067623e-311 1.78021527e-306]]


array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [130]:
#Write a NumPy program to find the real and imaginary parts of an array of complex numbers.
import numpy as np
x=np.sqrt([1+0j])
y=np.sqrt([0+1j])
print(x)
print(y)
print('real no')
print(x.real)
print(y.real)
print('imag no')
print(x.imag)
print(y.imag)


[1.+0.j]
[0.70710678+0.70710678j]
real no
[1.]
[0.70710678]
imag no
[0.]
[0.70710678]
